//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;

public partial class TurPaylasimEntities : DbContext
{
    public TurPaylasimEntities()
        : base("name=TurPaylasimEntities")
    {
    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }

    public virtual DbSet<tblAdmin> tblAdmin { get; set; }
    public virtual DbSet<tblKategori> tblKategori { get; set; }
    public virtual DbSet<tblMesajlar> tblMesajlar { get; set; }
    public virtual DbSet<tblOdeme> tblOdeme { get; set; }
    public virtual DbSet<tblRehber> tblRehber { get; set; }
    public virtual DbSet<tblSertifikalar> tblSertifikalar { get; set; }
    public virtual DbSet<tblSlider> tblSlider { get; set; }
    public virtual DbSet<tblTur> tblTur { get; set; }
    public virtual DbSet<tblTuraKatilanlar> tblTuraKatilanlar { get; set; }
    public virtual DbSet<tblUye> tblUye { get; set; }
}
