//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class tblAdmin
{
    public int Id { get; set; }
    public string Ad { get; set; }
    public string Soyad { get; set; }
    public string Sifre { get; set; }
    public string KullaniciAdi { get; set; }
    public string Mail { get; set; }
    public string Tel { get; set; }
    public string Durumu { get; set; }
    public Nullable<System.DateTime> BaslangicTarihi { get; set; }
}

public partial class tblKategori
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblKategori()
    {
        this.tblTur = new HashSet<tblTur>();
    }

    public int Id { get; set; }
    public string KategoriAdi { get; set; }
    public string KategoriAciklama { get; set; }
    public string Durumu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblTur> tblTur { get; set; }
}

public partial class tblMesajlar
{
    public int Id { get; set; }
    public string Ad { get; set; }
    public string Soyad { get; set; }
    public string Mail { get; set; }
    public string Mesaj { get; set; }
    public Nullable<System.DateTime> MesajTarihi { get; set; }
}

public partial class tblOdeme
{
    public int Id { get; set; }
    public string KartNo { get; set; }
    public string CVV { get; set; }
    public string KartSahibi { get; set; }
    public string SKT { get; set; }
    public Nullable<System.DateTime> OdemeTarihi { get; set; }
    public Nullable<int> TurId { get; set; }
    public Nullable<int> UyeId { get; set; }
    public string Durum { get; set; }

    public virtual tblTur tblTur { get; set; }
    public virtual tblUye tblUye { get; set; }
}

public partial class tblRehber
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblRehber()
    {
        this.tblTur = new HashSet<tblTur>();
        this.tblTuraKatilanlar = new HashSet<tblTuraKatilanlar>();
    }

    public int Id { get; set; }
    public string Ad { get; set; }
    public string Soyad { get; set; }
    public string TCKN { get; set; }
    public string Sifre { get; set; }
    public string KullaniciAdi { get; set; }
    public string Mail { get; set; }
    public string Telefon { get; set; }
    public string SertifikaYolu { get; set; }
    public string Durumu { get; set; }
    public Nullable<System.DateTime> UyelikTarihi { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblTur> tblTur { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblTuraKatilanlar> tblTuraKatilanlar { get; set; }
}

public partial class tblSertifikalar
{
    public int Id { get; set; }
    public string Ad { get; set; }
    public string Yolu { get; set; }
    public string Durumu { get; set; }
    public Nullable<int> RehberId { get; set; }
}

public partial class tblSlider
{
    public byte Id { get; set; }
    public string DosyaAdi { get; set; }
    public Nullable<int> SiraNo { get; set; }
    public string Fotograf { get; set; }
}

public partial class tblTur
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblTur()
    {
        this.tblOdeme = new HashSet<tblOdeme>();
        this.tblTuraKatilanlar = new HashSet<tblTuraKatilanlar>();
    }

    public int Id { get; set; }
    public string Ad { get; set; }
    public string Aciklama { get; set; }
    public Nullable<decimal> Fiyat { get; set; }
    public string Durumu { get; set; }
    public Nullable<System.DateTime> BaslangicTarihi { get; set; }
    public Nullable<System.DateTime> BitisTarihi { get; set; }
    public Nullable<System.DateTime> OlusturulmaTarihi { get; set; }
    public string TurResim { get; set; }
    public Nullable<int> KategoriId { get; set; }
    public Nullable<int> RehberId { get; set; }

    public virtual tblKategori tblKategori { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblOdeme> tblOdeme { get; set; }
    public virtual tblRehber tblRehber { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblTuraKatilanlar> tblTuraKatilanlar { get; set; }
}

public partial class tblTuraKatilanlar
{
    public int Id { get; set; }
    public Nullable<int> UyeId { get; set; }
    public Nullable<int> TurId { get; set; }
    public Nullable<int> RehberId { get; set; }
    public Nullable<decimal> Fiyat { get; set; }

    public virtual tblTur tblTur { get; set; }
    public virtual tblUye tblUye { get; set; }
    public virtual tblRehber tblRehber { get; set; }
}

public partial class tblUye
{
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public tblUye()
    {
        this.tblOdeme = new HashSet<tblOdeme>();
        this.tblTuraKatilanlar = new HashSet<tblTuraKatilanlar>();
    }

    public int Id { get; set; }
    public string Ad { get; set; }
    public string Soyad { get; set; }
    public string Sifre { get; set; }
    public string Mail { get; set; }
    public string Tel { get; set; }
    public string KullaniciAdi { get; set; }
    public Nullable<System.DateTime> UyelikTarihi { get; set; }
    public string Durumu { get; set; }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblOdeme> tblOdeme { get; set; }
    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
    public virtual ICollection<tblTuraKatilanlar> tblTuraKatilanlar { get; set; }
}
